using System;
using System.Linq;

namespace I18Next.Net.Internal;

// TODO Integrate https://github.com/mj1856/TimeZoneNames/
// Like mentioned here https://stackoverflow.com/questions/15302083/timezone-abbreviations
public class TimeZoneData
{
    public static TimeZoneData[] DefaultTimeZones =
    {
        new("A", "Alpha Time Zone", "Military", +1, 0),
        new("ACDT", "Australian Central Daylight Time", "Australia", +10, 30),
        new("ACST", "Australian Central Standard Time", "Australia", +9, 30),
        new("ACT", "Acre Time", "South America", -5, 0),
        new("ACT", "Australian Central Time", "Australia", +9, 30),
        new("ACWST", "Australian Central Western Standard Time", "Australia", +8, 45),
        new("ADT", "Arabia Daylight Time", "Asia", +4, 0),
        new("ADT", "Atlantic Daylight Time", "North America", -3, 0),
        new("AEDT", "Australian Eastern Daylight Time", "Australia", +11, 0),
        new("AEST", "Australian Eastern Standard Time", "Australia", +10, 0),
        new("AET", "Australian Eastern Time", "Australia", +10, 00),
        new("AFT", "Afghanistan Time", "Asia", +4, 30),
        new("AKDT", "Alaska Daylight Time", "North America", -8, 0),
        new("AKST", "Alaska Standard Time", "North America", -9, 0),
        new("ALMT", "Alma-Ata Time", "Asia", +6, 0),
        new("AMST", "Amazon Summer Time", "South America", -3, 0),
        new("AMST", "Armenia Summer Time", "Asia", +5, 0),
        new("AMT", "Amazon Time", "South America", -4, 0),
        new("AMT", "Armenia Time", "Asia", +4, 0),
        new("ANAST", "Anadyr Summer Time", "Asia", +12, 0),
        new("ANAT", "Anadyr Time", "Asia", +12, 0),
        new("AQTT", "Aqtobe Time", "Asia", +5, 0),
        new("ART", "Argentina Time", "Antarctica", -3, 0),
        new("AST", "Arabia Standard Time", "Asia", +3, 0),
        new("AST", "Atlantic Standard Time", "North America", -4, 0),
        new("AT", "Atlantic Time", "North America", -4, 00),
        new("AWDT", "Australian Western Daylight Time", "Australia", +9, 0),
        new("AWST", "Australian Western Standard Time", "Australia", +8, 0),
        new("AZOST", "Azores Summer Time", "Atlantic", +0, 0),
        new("AZOT", "Azores Time", "Atlantic", -1, 0),
        new("AZST", "Azerbaijan Summer Time", "Asia", +5, 0),
        new("AZT", "Azerbaijan Time", "Asia", +4, 0),
        new("AoE", "Anywhere on Earth", "Pacific", -12, 0),
        new("B", "Bravo Time Zone", "Military", +2, 0),
        new("BNT", "Brunei Darussalam Time", "Asia", +8, 0),
        new("BOT", "Bolivia Time", "South America", -4, 0),
        new("BRST", "Brasília Summer Time", "South America", -2, 0),
        new("BRT", "Brasília Time", "South America", -3, 0),
        new("BST", "Bangladesh Standard Time", "Asia", +6, 0),
        new("BST", "Bougainville Standard Time", "Pacific", +11, 0),
        new("BST", "British Summer Time", "Europe", +1, 0),
        new("BTT", "Bhutan Time", "Asia", +6, 0),
        new("C", "Charlie Time Zone", "Military", +3, 0),
        new("CAST", "Casey Time", "Antarctica", +8, 0),
        new("CAT", "Central Africa Time", "Africa", +2, 0),
        new("CCT", "Cocos Islands Time", "Indian Ocean", +6, 30),
        new("CDT", "Central Daylight Time", "North America", -5, 0),
        new("CDT", "Cuba Daylight Time", "Caribbean", -4, 0),
        new("CEST", "Central European Summer Time", "Europe", +2, 0),
        new("CET", "Central European Time", "Europe", +1, 0),
        new("CHADT", "Chatham Island Daylight Time", "Pacific", +13, 45),
        new("CHAST", "Chatham Island Standard Time", "Pacific", +12, 45),
        new("CHOST", "Choibalsan Summer Time", "Asia", +9, 0),
        new("CHOT", "Choibalsan Time", "Asia", +8, 0),
        new("CHUT", "Chuuk Time", "Pacific", +10, 0),
        new("CIDST", "Cayman Islands Daylight Saving Time", "Caribbean", -4, 0),
        new("CIST", "Cayman Islands Standard Time", "Caribbean", -5, 0),
        new("CKT", "Cook Island Time", "Pacific", -10, 0),
        new("CLST", "Chile Summer Time", "South America", -3, 0),
        new("CLT", "Chile Standard Time", "South America", -4, 0),
        new("COT", "Colombia Time", "South America", -5, 0),
        new("CST", "Central Standard Time", "North America", -6, 0),
        new("CST", "China Standard Time", "Asia", +8, 0),
        new("CST", "Cuba Standard Time", "Caribbean", -5, 0),
        new("CT", "Central Time", "North America", -6, 00),
        new("CVT", "Cape Verde Time", "Africa", -1, 0),
        new("CXT", "Christmas Island Time", "Australia", +7, 0),
        new("ChST", "Chamorro Standard Time", "Pacific", +10, 0),
        new("D", "Delta Time Zone", "Military", +4, 0),
        new("DAVT", "Davis Time", "Antarctica", +7, 0),
        new("DDUT", "Dumont-d'Urville Time", "Antarctica", +10, 0),
        new("E", "Echo Time Zone", "Military", +5, 0),
        new("EASST", "Easter Island Summer Time", "Pacific", -5, 0),
        new("EAST", "Easter Island Standard Time", "Pacific", -6, 0),
        new("EAT", "Eastern Africa Time", "Africa", +3, 0),
        new("ECT", "Ecuador Time", "South America", -5, 0),
        new("EDT", "Eastern Daylight Time", "North America", -4, 0),
        new("EEST", "Eastern European Summer Time", "Europe", +3, 0),
        new("EET", "Eastern European Time", "Europe", +2, 0),
        new("EGST", "Eastern Greenland Summer Time", "North America", +0, 0),
        new("EGT", "East Greenland Time", "North America", -1, 0),
        new("EST", "Eastern Standard Time", "North America", -5, 0),
        new("ET", "Eastern Time", "North America", -5, 00),
        new("F", "Foxtrot Time Zone", "Military", +6, 0),
        new("FET", "Further-Eastern European Time", "Europe", +3, 0),
        new("FJST", "Fiji Summer Time", "Pacific", +13, 0),
        new("FJT", "Fiji Time", "Pacific", +12, 0),
        new("FKST", "Falkland Islands Summer Time", "South America", -3, 0),
        new("FKT", "Falkland Island Time", "South America", -4, 0),
        new("FNT", "Fernando de Noronha Time", "South America", -2, 0),
        new("G", "Golf Time Zone", "Military", +7, 0),
        new("GALT", "Galapagos Time", "Pacific", -6, 0),
        new("GAMT", "Gambier Time", "Pacific", -9, 0),
        new("GET", "Georgia Standard Time", "Asia", +4, 0),
        new("GFT", "French Guiana Time", "South America", -3, 0),
        new("GILT", "Gilbert Island Time", "Pacific", +12, 0),
        new("GMT", "Greenwich Mean Time", "Europe", +0, 0),
        new("GST", "Gulf Standard Time", "Asia", +4, 0),
        new("GST", "South Georgia Time", "South America", -2, 0),
        new("GYT", "Guyana Time", "South America", -4, 0),
        new("H", "Hotel Time Zone", "Military", +8, 0),
        new("HDT", "Hawaii-Aleutian Daylight Time", "North America", -9, 0),
        new("HKT", "Hong Kong Time", "Asia", +8, 0),
        new("HOVST", "Hovd Summer Time", "Asia", +8, 0),
        new("HOVT", "Hovd Time", "Asia", +7, 0),
        new("HST", "Hawaii Standard Time", "North America", -10, 0),
        new("I", "India Time Zone", "Military", +9, 0),
        new("ICT", "Indochina Time", "Asia", +7, 0),
        new("IDT", "Israel Daylight Time", "Asia", +3, 0),
        new("IOT", "Indian Chagos Time", "Indian Ocean", +6, 0),
        new("IRDT", "Iran Daylight Time", "Asia", +4, 30),
        new("IRKST", "Irkutsk Summer Time", "Asia", +9, 0),
        new("IRKT", "Irkutsk Time", "Asia", +8, 0),
        new("IRST", "Iran Standard Time", "Asia", +3, 30),
        new("IST", "India Standard Time", "Asia", +5, 30),
        new("IST", "Irish Standard Time", "Europe", +1, 0),
        new("IST", "Israel Standard Time", "Asia", +2, 0),
        new("JST", "Japan Standard Time", "Asia", +9, 0),
        new("K", "Kilo Time Zone", "Military", +10, 0),
        new("KGT", "Kyrgyzstan Time", "Asia", +6, 0),
        new("KOST", "Kosrae Time", "Pacific", +11, 0),
        new("KRAST", "Krasnoyarsk Summer Time", "Asia", +8, 0),
        new("KRAT", "Krasnoyarsk Time", "Asia", +7, 0),
        new("KST", "Korea Standard Time", "Asia", +9, 0),
        new("KUYT", "Kuybyshev Time", "Europe", +4, 0),
        new("L", "Lima Time Zone", "Military", +11, 0),
        new("LHDT", "Lord Howe Daylight Time", "Australia", +11, 0),
        new("LHST", "Lord Howe Standard Time", "Australia", +10, 30),
        new("LINT", "Line Islands Time", "Pacific", +14, 0),
        new("M", "Mike Time Zone", "Military", +12, 0),
        new("MAGST", "Magadan Summer Time", "Asia", +12, 0),
        new("MAGT", "Magadan Time", "Asia", +11, 0),
        new("MART", "Marquesas Time", "Pacific", -9, 30),
        new("MAWT", "Mawson Time", "Antarctica", +5, 0),
        new("MDT", "Mountain Daylight Time", "North America", -6, 0),
        new("MHT", "Marshall Islands Time", "Pacific", +12, 0),
        new("MMT", "Myanmar Time", "Asia", +6, 30),
        new("MSD", "Moscow Daylight Time", "Europe", +4, 0),
        new("MSK", "Moscow Standard Time", "Europe", +3, 0),
        new("MST", "Mountain Standard Time", "North America", -7, 0),
        new("MT", "Mountain Time", "North America", -7, 00),
        new("MUT", "Mauritius Time", "Africa", +4, 0),
        new("MVT", "Maldives Time", "Asia", +5, 0),
        new("MYT", "Malaysia Time", "Asia", +8, 0),
        new("N", "November Time Zone", "Military", -1, 0),
        new("NCT", "New Caledonia Time", "Pacific", +11, 0),
        new("NDT", "Newfoundland Daylight Time", "North America", -2, 30),
        new("NFT", "Norfolk Time", "Australia", +11, 0),
        new("NOVST", "Novosibirsk Summer Time", "Asia", +7, 0),
        new("NOVT", "Novosibirsk Time", "Asia", +6, 0),
        new("NPT", "Nepal Time", "Asia", +5, 45),
        new("NRT", "Nauru Time", "Pacific", +12, 0),
        new("NST", "Newfoundland Standard Time", "North America", -3, 30),
        new("NUT", "Niue Time", "Pacific", -11, 0),
        new("NZDT", "New Zealand Daylight Time", "Pacific", +13, 0),
        new("NZST", "New Zealand Standard Time", "Pacific", +12, 0),
        new("O", "Oscar Time Zone", "Military", -2, 0),
        new("OMSST", "Omsk Summer Time", "Asia", +7, 0),
        new("OMST", "Omsk Standard Time", "Asia", +6, 0),
        new("ORAT", "Oral Time", "Asia", +5, 0),
        new("P", "Papa Time Zone", "Military", -3, 0),
        new("PDT", "Pacific Daylight Time", "North America", -7, 0),
        new("PET", "Peru Time", "South America", -5, 0),
        new("PETST", "Kamchatka Summer Time", "Asia", +12, 0),
        new("PETT", "Kamchatka Time", "Asia", +12, 0),
        new("PGT", "Papua New Guinea Time", "Pacific", +10, 0),
        new("PHOT", "Phoenix Island Time", "Pacific", +13, 0),
        new("PHT", "Philippine Time", "Asia", +8, 0),
        new("PKT", "Pakistan Standard Time", "Asia", +5, 0),
        new("PMDT", "Pierre & Miquelon Daylight Time", "North America", -2, 0),
        new("PMST", "Pierre & Miquelon Standard Time", "North America", -3, 0),
        new("PONT", "Pohnpei Standard Time", "Pacific", +11, 0),
        new("PST", "Pacific Standard Time", "North America", -8, 0),
        new("PST", "Pitcairn Standard Time", "Pacific", -8, 0),
        new("PT", "Pacific Time", "North America", -8, 00),
        new("PWT", "Palau Time", "Pacific", +9, 0),
        new("PYST", "Paraguay Summer Time", "South America", -3, 0),
        new("PYT", "Paraguay Time", "South America", -4, 0),
        new("PYT", "Pyongyang Time", "Asia", +8, 30),
        new("Q", "Quebec Time Zone", "Military", -4, 0),
        new("QYZT", "Qyzylorda Time", "Asia", +6, 0),
        new("R", "Romeo Time Zone", "Military", -5, 0),
        new("RET", "Reunion Time", "Africa", +4, 0),
        new("ROTT", "Rothera Time", "Antarctica", -3, 0),
        new("S", "Sierra Time Zone", "Military", -6, 0),
        new("SAKT", "Sakhalin Time", "Asia", +11, 0),
        new("SAMT", "Samara Time", "Europe", +4, 0),
        new("SAST", "South Africa Standard Time", "Africa", +2, 0),
        new("SBT", "Solomon Islands Time", "Pacific", +11, 0),
        new("SCT", "Seychelles Time", "Africa", +4, 0),
        new("SGT", "Singapore Time", "Asia", +8, 0),
        new("SRET", "Srednekolymsk Time", "Asia", +11, 0),
        new("SRT", "Suriname Time", "South America", -3, 0),
        new("SST", "Samoa Standard Time", "Pacific", -11, 0),
        new("SYOT", "Syowa Time", "Antarctica", +3, 0),
        new("T", "Tango Time Zone", "Military", -7, 0),
        new("TAHT", "Tahiti Time", "Pacific", -10, 0),
        new("TFT", "French Southern and Antarctic Time", "Indian Ocean", +5, 0),
        new("TJT", "Tajikistan Time", "Asia", +5, 0),
        new("TKT", "Tokelau Time", "Pacific", +13, 0),
        new("TLT", "East Timor Time", "Asia", +9, 0),
        new("TMT", "Turkmenistan Time", "Asia", +5, 0),
        new("TOST", "Tonga Summer Time", "Pacific", +14, 0),
        new("TOT", "Tonga Time", "Pacific", +13, 0),
        new("TRT", "Turkey Time", "Asia", +3, 0),
        new("TVT", "Tuvalu Time", "Pacific", +12, 0),
        new("U", "Uniform Time Zone", "Military", -8, 0),
        new("ULAST", "Ulaanbaatar Summer Time", "Asia", +9, 0),
        new("ULAT", "Ulaanbaatar Time", "Asia", +8, 0),
        new("UTC", "Coordinated Universal Time", "Worldwide", 0, 0),
        new("UYST", "Uruguay Summer Time", "South America", -2, 0),
        new("UYT", "Uruguay Time", "South America", -3, 0),
        new("UZT", "Uzbekistan Time", "Asia", +5, 0),
        new("V", "Victor Time Zone", "Military", -9, 0),
        new("VET", "Venezuelan Standard Time", "South America", -4, 0),
        new("VLAST", "Vladivostok Summer Time", "Asia", +11, 0),
        new("VLAT", "Vladivostok Time", "Asia", +10, 0),
        new("VOST", "Vostok Time", "Antarctica", +6, 0),
        new("VUT", "Vanuatu Time", "Pacific", +11, 0),
        new("W", "Whiskey Time Zone", "Military", -10, 0),
        new("WAKT", "Wake Time", "Pacific", +12, 0),
        new("WARST", "Western Argentine Summer Time", "South America", -3, 0),
        new("WAST", "West Africa Summer Time", "Africa", +2, 0),
        new("WAT", "West Africa Time", "Africa", +1, 0),
        new("WEST", "Western European Summer Time", "Europe", +1, 0),
        new("WET", "Western European Time", "Europe", +0, 0),
        new("WFT", "Wallis and Futuna Time", "Pacific", +12, 0),
        new("WGST", "Western Greenland Summer Time", "North America", -2, 0),
        new("WGT", "West Greenland Time", "North America", -3, 0),
        new("WIB", "Western Indonesian Time", "Asia", +7, 0),
        new("WIT", "Eastern Indonesian Time", "Asia", +9, 0),
        new("WITA", "Central Indonesian Time", "Asia", +8, 0),
        new("WST", "West Samoa Time", "Pacific", +13, 0),
        new("WST", "Western Sahara Summer Time", "Africa", +1, 0),
        new("WT", "Western Sahara Standard Time", "Africa", +0, 0),
        new("X", "X-ray Time Zone", "Military", -11, 0),
        new("Y", "Yankee Time Zone", "Military", -12, 0),
        new("YAKST", "Yakutsk Summer Time", "Asia", +10, 0),
        new("YAKT", "Yakutsk Time", "Asia", +9, 0),
        new("YAPT", "Yap Time", "Pacific", +10, 0),
        new("YEKST", "Yekaterinburg Summer Time", "Asia", +6, 0),
        new("YEKT", "Yekaterinburg Time", "Asia", +5, 0),
        new("Z", "Zulu Time Zone", "Military", +0, 0)
    };


    public TimeZoneData(string abbr, string name, string continent, int hourOffset, int minuteOffset)
    {
        var offset = TimeSpan.FromHours(hourOffset);

        offset = offset.Add(hourOffset < 0 ? TimeSpan.FromMinutes(-minuteOffset) : TimeSpan.FromMinutes(minuteOffset));

        Abbreviation = abbr;
        Name = name;
        Continent = continent;
        Offset = offset;
    }

    public string Abbreviation { get; }

    public string Continent { get; }

    public string Name { get; }

    public TimeSpan Offset { get; }

    public static TimeZoneData GetFirstForOffset(TimeSpan offset)
    {
        return DefaultTimeZones.FirstOrDefault(tz => tz.Offset == offset);
    }

    public static TimeZoneData GetFirstForOffset(string continent, TimeSpan offset)
    {
        return DefaultTimeZones.FirstOrDefault(tz => tz.Continent == continent && tz.Offset == offset);
    }
}
