<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\I18Next.Net.AspNetCore\I18Next.Net.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\I18Next.Net.Extensions\I18Next.Net.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="locales\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
