<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
        <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">$(TargetFrameworks);net48</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <LangVersion>Latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="FluentAssertions" Version="6.12.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="nunit" Version="3.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\I18Next.Net.Extensions\I18Next.Net.Extensions.csproj" />
        <ProjectReference Include="..\..\src\I18Next.Net\I18Next.Net.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Remove="Backends\TestFiles\de\test.ini" />
        <None Remove="Backends\TestFiles\en-US\test.ini" />
        <None Update="TestFiles\de\test.ini">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\en-US\test.ini">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\de\test.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\en-US\test.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\de\test.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\en-US\test.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\de\test-strict.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\en-US\test-strict.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\en-US\types.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\custom\test_en.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\cldr\*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\objects\**\*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestFiles\plurals\**\*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>