<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <IsPackable>false</IsPackable>
        <LangVersion>Latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\I18Next.Net.Wpf\I18Next.Net.Wpf.csproj" />
    </ItemGroup>
</Project>
