using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using I18Next.Net.Tool.Resources;

namespace I18Next.Net.Tool.Extraction;

/// <summary>
///     Decides whether a translation key is used by the extracted keys or by nestings in translations. Plural and context
///     variants and the children of a used key count as used.
/// </summary>
internal sealed class KeyUsage(string keySeparator, string namespaceSeparator)
{
    private readonly HashSet<(string Namespace, string Key)> _keys = [];
    private IReadOnlyCollection<string> _memberChains;

    public void Add(ExtractedKey key)
    {
        _keys.Add((key.Namespace, key.Key));
    }

    public void AddRange(IEnumerable<ExtractedKey> keys)
    {
        foreach (var key in keys)
            Add(key);
    }

    /// <summary>
    ///     Marks the keys nested with <c>$t(key)</c> in a translation as used.
    /// </summary>
    public void AddNestings(string @namespace, string text)
    {
        foreach (var nestedKey in Placeholders.GetNestedKeys(text))
        {
            var separatorIndex = string.IsNullOrEmpty(namespaceSeparator) ? -1 : nestedKey.IndexOf(namespaceSeparator, StringComparison.Ordinal);

            _keys.Add(separatorIndex > 0
                ? (nestedKey.Substring(0, separatorIndex), nestedKey.Substring(separatorIndex + namespaceSeparator.Length))
                : (@namespace, nestedKey));
        }
    }

    /// <summary>
    ///     Marks the keys as used whose members generated by I18Next.Net.Generators, e.g. <c>Cart.Items</c> for
    ///     <c>cart.items</c>, are accessed.
    /// </summary>
    public void AddGeneratedMemberChains(IReadOnlyCollection<string> memberChains)
    {
        _memberChains = memberChains;
    }

    public bool IsUsed(string @namespace, string key)
    {
        if (IsUsedExactly(@namespace, key))
            return true;

        for (var i = key.Length - 1; i > 0; i--)
        {
            var isVariant = string.CompareOrdinal(key, i, PluralForms.Separator, 0, PluralForms.Separator.Length) == 0;
            var isChild = keySeparator.Length > 0 && string.CompareOrdinal(key, i, keySeparator, 0, keySeparator.Length) == 0;

            if ((isVariant || isChild) && IsUsedExactly(@namespace, key.Substring(0, i)))
                return true;
        }

        return false;
    }

    private bool IsUsedExactly(string @namespace, string key)
    {
        return _keys.Contains((@namespace, key)) || (_memberChains != null && _memberChains.Contains(GetMemberChain(key)));
    }

    private string GetMemberChain(string key)
    {
        var segments = keySeparator.Length == 0 ? [key] : key.Split([keySeparator], StringSplitOptions.None);

        return string.Join(".", segments.Select(ToPascalCase));
    }

    private static string ToPascalCase(string value)
    {
        var builder = new StringBuilder(value.Length);
        var upper = true;

        foreach (var c in value)
        {
            if (!char.IsLetterOrDigit(c))
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(c) : c);
            upper = false;
        }

        if (builder.Length == 0)
            return "Key";

        return char.IsDigit(builder[0]) ? "_" + builder : builder.ToString();
    }
}
