<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <LangVersion>Latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\I18Next.Net\I18Next.Net.csproj" />
        <ProjectReference Include="..\..\src\I18Next.Net.Generators\I18Next.Net.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    </ItemGroup>
    <ItemGroup>
        <AdditionalFiles Include="Locales\**\*.json" />
        <None Update="Locales\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
