<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net6.0;net8.0;net10.0</TargetFrameworks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DocumentationFile>bin\Debug\I18Next.Net.AspNetCore.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\I18Next.Net.AspNetCore.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Localization" Version="2.3.13" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\I18Next.Net.Extensions\I18Next.Net.Extensions.csproj" />
      <ProjectReference Include="..\I18Next.Net\I18Next.Net.csproj" />
    </ItemGroup>

</Project>
