using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace I18Next.Net.Generators;

internal sealed class SourceEmitter
{
    private const string GeneratedCode = "[global::System.CodeDom.Compiler.GeneratedCode(\"I18Next.Net.Generators\", \"1.0.0\")]";
    private const string I18Next = "global::I18Next.Net.II18Next";
    private const string Task = "global::System.Threading.Tasks.Task";
    private const string ObjectDictionary = "global::System.Collections.Generic.IDictionary<string, object>";

    private readonly StringBuilder _builder = new();
    private readonly ResourceTarget _target;
    private int _indent;

    private SourceEmitter(ResourceTarget target)
    {
        _target = target;
    }

    public static string Emit(ResourceTarget target, IReadOnlyList<GroupModel> namespaces)
    {
        var emitter = new SourceEmitter(target);
        emitter.EmitFile(namespaces);

        return emitter._builder.ToString();
    }

    private void EmitFile(IReadOnlyList<GroupModel> namespaces)
    {
        Line("// <auto-generated/>");
        Line("#nullable disable");
        Line();

        if (_target.Namespace != null)
        {
            Line($"namespace {_target.Namespace}");
            Open();
        }

        foreach (var containingType in _target.ContainingTypes)
        {
            Line(containingType);
            Open();
        }

        Line(_target.TypeDeclaration);
        Open();

        var scope = new NameScope(_target.Name, "Keys", "__Translate", "__TranslateAsync", "__TranslateArray", "__TranslateArrayAsync");
        var keysScope = new NameScope("Keys");
        var accessors = namespaces.Select(n => (Model: n, Name: NameScope.ToPascalCase(n.Name))).ToList();

        Line(GeneratedCode);
        Line("public static class Keys");
        Open();

        foreach (var (model, name) in accessors)
            EmitKeys(model, keysScope.Add(name), model.Name);

        Close();

        foreach (var (model, name) in accessors)
        {
            var accessorName = scope.Add(name);
            var typeName = scope.Add(name + "Namespace");
            var @this = _target.SupportsExtensions ? "this " : "";

            Line();
            Line($"/// <summary>Typed translations of the namespace <c>{Xml(model.Name)}</c>.</summary>");
            Line($"public static {typeName} {accessorName}({@this}{I18Next} i18n) => new {typeName}(i18n);");
            Line();
            EmitGroup(model, typeName, model.Name);
        }

        Line();
        Line($"private static string __Translate({I18Next} i18n, string language, string key, object args) => language == null ? i18n.T(key, args) : i18n.T(language, key, args);");
        Line();
        Line($"private static {Task}<string> __TranslateAsync({I18Next} i18n, string language, string key, object args) => language == null ? i18n.Ta(key, args) : i18n.Ta(language, key, args);");
        Line();
        Line($"private static string[] __TranslateArray({I18Next} i18n, string language, string key, object args) => language == null ? i18n.T<string[]>(key, args) : i18n.T<string[]>(language, key, args);");
        Line();
        Line($"private static {Task}<string[]> __TranslateArrayAsync({I18Next} i18n, string language, string key, object args) => language == null ? i18n.Ta<string[]>(key, args) : i18n.Ta<string[]>(language, key, args);");

        Close();

        foreach (var _ in _target.ContainingTypes)
            Close();

        if (_target.Namespace != null)
            Close();
    }

    private void EmitKeys(GroupModel group, string className, string @namespace)
    {
        var scope = new NameScope(className);

        Line($"public static class {className}");
        Open();

        if (group.FullKey.Length > 0)
            Line($"public const string {scope.Add("Key")} = {NameScope.ToLiteral(GetKey(@namespace, group.FullKey))};");

        foreach (var key in group.Keys)
            Line($"public const string {scope.Add(NameScope.ToPascalCase(key.Name))} = {NameScope.ToLiteral(GetKey(@namespace, key.FullKey))};");

        foreach (var child in group.Groups)
            EmitKeys(child, scope.Add(NameScope.ToPascalCase(child.Name)), @namespace);

        Close();
    }

    private void EmitGroup(GroupModel group, string typeName, string @namespace)
    {
        var scope = new NameScope(typeName, "_i18n", "ToObject", "ToObjectAsync", "To", "ToAsync");

        Line(GeneratedCode);
        Line($"public readonly struct {typeName}");
        Open();
        Line($"private readonly {I18Next} _i18n;");
        Line();
        Line($"public {typeName}({I18Next} i18n)");
        Open();
        Line("_i18n = i18n;");
        Close();

        if (group.FullKey.Length > 0)
        {
            var key = NameScope.ToLiteral(GetKey(@namespace, group.FullKey));

            Line();
            Line($"public {ObjectDictionary} ToObject(object args = null, string language = null) => language == null ? _i18n.TObject({key}, args) : _i18n.TObject(language, {key}, args);");
            Line();
            Line($"public {Task}<{ObjectDictionary}> ToObjectAsync(object args = null, string language = null) => language == null ? _i18n.TaObject({key}, args) : _i18n.TaObject(language, {key}, args);");
            Line();
            Line($"public TModel To<TModel>(object args = null, string language = null) => language == null ? _i18n.T<TModel>({key}, args) : _i18n.T<TModel>(language, {key}, args);");
            Line();
            Line($"public {Task}<TModel> ToAsync<TModel>(object args = null, string language = null) => language == null ? _i18n.Ta<TModel>({key}, args) : _i18n.Ta<TModel>(language, {key}, args);");
        }

        foreach (var key in group.Keys)
            EmitKey(key, scope, @namespace);

        foreach (var child in group.Groups)
        {
            var propertyName = scope.Add(NameScope.ToPascalCase(child.Name));
            var childTypeName = scope.Add(propertyName + "Group");

            Line();
            Line($"public {childTypeName} {propertyName} => new {childTypeName}(_i18n);");
            Line();
            EmitGroup(child, childTypeName, @namespace);
        }

        Close();
    }

    private void EmitKey(KeyModel key, NameScope scope, string @namespace)
    {
        var name = NameScope.ToPascalCase(key.Name);

        while (true)
        {
            var candidate = scope.Add(name);

            if (scope.TryAdd(candidate + "Async"))
            {
                name = candidate;
                break;
            }

            name = candidate + "_";
        }

        var parameterScope = new NameScope(name, "args", "language", "count", "context", "ordinal");
        var parameters = new List<string>();
        var assignments = new List<string>();

        var optionalCount = key.Plural && (key.Simple || key.Contexts.Count > 0);

        if (key.Plural && !optionalCount)
        {
            parameters.Add("int count");
            assignments.Add("args[\"count\"] = count;");
        }

        foreach (var placeholder in key.Placeholders)
        {
            if ((placeholder == "count" && key.Plural) || (placeholder == "context" && key.Contexts.Count > 0))
                continue;

            var parameterName = parameterScope.Add(NameScope.ToParameterName(placeholder));
            parameters.Add($"object {parameterName}");
            assignments.Add($"args[{NameScope.ToLiteral(placeholder)}] = {parameterName};");
        }

        if (optionalCount)
        {
            parameters.Add("int? count = null");
            assignments.Add("if (count != null) args[\"count\"] = count.Value;");
        }

        if (key.Contexts.Count > 0)
        {
            parameters.Add("string context = null");
            assignments.Add("if (context != null) args[\"context\"] = context;");
        }

        if (key.Ordinal && key.Cardinal)
        {
            parameters.Add("bool ordinal = false");
            assignments.Add("if (ordinal) args[\"ordinal\"] = true;");
        }
        else if (key.Ordinal)
        {
            assignments.Add("args[\"ordinal\"] = true;");
        }

        parameters.Add("string language = null");

        var literal = NameScope.ToLiteral(GetKey(@namespace, key.FullKey));
        var parameterList = string.Join(", ", parameters);
        var returnType = key.IsArray ? "string[]" : "string";
        var helper = key.IsArray ? "__TranslateArray" : "__Translate";

        foreach (var async in new[] { false, true })
        {
            Line();
            EmitDocumentation(key);
            Line($"public {(async ? $"{Task}<{returnType}>" : returnType)} {name}{(async ? "Async" : "")}({parameterList})");
            Open();

            if (assignments.Count == 0)
            {
                Line($"return {helper}{(async ? "Async" : "")}(_i18n, language, {literal}, null);");
            }
            else
            {
                Line($"var args = new global::System.Collections.Generic.Dictionary<string, object>({assignments.Count});");

                foreach (var assignment in assignments)
                    Line(assignment);

                Line($"return {helper}{(async ? "Async" : "")}(_i18n, language, {literal}, args);");
            }

            Close();
        }
    }

    private void EmitDocumentation(KeyModel key)
    {
        var details = new List<string>();

        if (key.Cardinal)
            details.Add("plural");

        if (key.Ordinal)
            details.Add("ordinal");

        if (key.Contexts.Count > 0)
            details.Add("contexts: " + string.Join(", ", key.Contexts));

        var summary = key.Example == null ? $"<c>{Xml(key.FullKey)}</c>" : $"<c>{Xml(key.FullKey)}</c>: {Xml(key.Example)}";

        if (details.Count > 0)
            summary += $" ({Xml(string.Join("; ", details))})";

        Line($"/// <summary>{summary.Replace("\r", "").Replace("\n", " ")}</summary>");
    }

    private string GetKey(string @namespace, string key)
    {
        return @namespace + _target.NamespaceSeparator + key;
    }

    private static string Xml(string value)
    {
        return value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }

    private void Open()
    {
        Line("{");
        _indent++;
    }

    private void Close()
    {
        _indent--;
        Line("}");
    }

    private void Line(string text = "")
    {
        if (text.Length > 0)
            _builder.Append(' ', _indent * 4);

        _builder.Append(text).Append('\n');
    }
}
