<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Backend for I18Next.Net reading YAML translation files.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <TargetFrameworks>netstandard2.0;net6.0;net8.0;net10.0</TargetFrameworks>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DocumentationFile>bin\Debug\I18Next.Net.Yaml.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\I18Next.Net.Yaml.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\I18Next.Net\I18Next.Net.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="YamlDotNet" Version="18.1.0" />
    </ItemGroup>

</Project>
