<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>A port of i18next for .NET with interpolation, plurals, context, nesting, browser compatible number, date, relative time and list formats and JSON, XML, INI, HTTP, delegate and in-memory backends.</Description>
        <TargetFrameworks>netstandard2.0;net6.0;net8.0;net10.0</TargetFrameworks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DocumentationFile>bin\Debug\I18Next.Net.xml</DocumentationFile>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\I18Next.Net.xml</DocumentationFile>
    </PropertyGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="System.Text.Json" Version="8.0.6" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\cldr.json.gz" LogicalName="I18Next.Net.Resources.cldr.json.gz" />
        <EmbeddedResource Include="Resources\date-fns.json.gz" LogicalName="I18Next.Net.Resources.date-fns.json.gz" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\I18Next.Net.Abstractions\I18Next.Net.Abstractions.csproj" />
    </ItemGroup>
</Project>
