<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>.NET MAUI integration for I18Next.Net with a markup extension whose translations update when the language or the translation files change.</Description>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DocumentationFile>bin\Debug\I18Next.Net.Maui.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\I18Next.Net.Maui.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
      <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.100" />
    </ItemGroup>

    <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
      <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\Shared\Xaml\*.cs" LinkBase="Shared" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\I18Next.Net.Extensions\I18Next.Net.Extensions.csproj" />
      <ProjectReference Include="..\I18Next.Net\I18Next.Net.csproj" />
    </ItemGroup>

</Project>
